dist: xenial

addons:
  apt:
    update: true
    packages: build-essential

before_script:
  - ./vendor-all.sh

script:
  - source vendor-env.sh
  # for nasm
  - export PATH=$PATH:$PREFIX/bin
  - go test -v ./...

